### ISSUE TITLE
Pretrained Models and Scalability

### ISSUE THREAD

**Issue by r2stanton** [idea-iitd/NeuroCUT#1]
Hello, just read the paper and love the project. Hope you don't mind me opening and issue for this, but feel free to close if you'd prefer. I'm just wondering if you plan on releasing any pre-trained models? If not, I'm curious about how well the framework scales up to systems with ~100k vertices, or whatever the largest is you've tried with the approach?

I'm also a bit confused about the `node_embedding.pt` that are mentioned as required at the bottom of the README for new graphs. So if I want to train on a new dataset of graphs with structure:

```
dataset/
 <1>
  ...
 <N>
```

where each folder contains a `graph.txt` and `graph_stats.txt`, it seems I still need more information when I go to train the model. Is this a set of node features/node embeddings? Would you be able to put an example on how to generate the embeddings? I wasn't clear if they should be simply copy/pasted from your example, but both approaches results in errors when trying to train on new data. I could generate my own embeddings with `nodevectors` or some similar code, but the issue then is that I'm not sure what size they should be, and if one is needed for each graph, or as in the example they seem to be defined once per dataset (outside of the raw_data/dataset/test-train-val folders).

I was under the impression from the paper that the code does these embeddings for you. But even if i set up the `graph.txt` and `graph_stats.txt` as suggested, the code won't compute and store the features/embeddings. So when I go to train on the new dataset I get:

```
Traceback (most recent call last):
  File "/users/stanton/installs/neurocut/src/main.py", line 131, in <module>
    train_dataset=dataset(dataset_path+'/train_set',embedding,norm,beta,device,args=args)
  File "/users/stanton/installs/neurocut/src/dataset.py", line 33, in __init__
    self.generate_features(1)
  File "/users/stanton/installs/neurocut/src/dataset.py", line 210, in generate_features
    features_given = torch.load(open(f2,"rb"))
UnboundLocalError: local variable 'f2' referenced before assignment
```

Thanks very much in advance for any information you can provide! 

Also I closed my issue on the other repository, I just realized this is the one for the official release.

**Comment by sahilm1992** [comment]
Hi,
Thanks for your interest in our work. We acknowledge your comment. We will get back to you on this soon.

**Comment by r2stanton** [comment]
Great thanks!

**Comment by rishi1001** [comment]
Thank you for your interest in our work. 

It seems you are trying to work on a new graph. If yes, then you can train and infer on a new dataset using either raw node features (generated or downloaded by you) combined with the Lipschitz node features (handled by the code). Refer to the `raw_dataset.py` file in the `raw_data` folder for instructions on downloading the raw node features.

Next, create an experiment in the `data` folder, which should contain `train`, `test`, and `val` subfolders. After setting up the experiment, you can run it. We have updated the README file for more detailed guidance.

Regarding your query on large graphs, we have tested our method on two large datasets (not included in the paper): coauthor (34,493 nodes) and ogbg-arxiv (137,900 nodes). We successfully trained on both, although we had to keep the trajectory length low (0.01% of nodes) due to long training times. However, we have not conducted any parameter studies on these two datasets as of now, so it is difficult to comment on the quality at the moment.

If you plan to use our method for very large graphs, batching will help (currently, node embeddings are processed altogether in line 295 in `src/main.py`, which can create scalability issues for a large number of nodes and node features). While this is not yet implemented, we plan to release it soon.

Additionally, as we follow a fully autoregressive approach, perturbing only one node at a time, the training and inference times are longer. Please refer to the Future Work section, where we discuss the possibility of perturbing multiple nodes simultaneously. This could reduce both training and inference times while still achieving competitive improvements.

In case you have any more questions, we are happy to help!

**Comment by r2stanton** [comment]
Awesome this information was very helpful, thank you very much!
